{{- if and .Values.istio.serviceEntry .Values.hosts -}}
{{ $super := . }}
{{- range .Values.hosts }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: "{{ include "tlsmonitor.fullname" $super }}-port-{{ .port }}"
spec:
  hosts:
{{- range .target }}
    - {{ . }}
{{- end}}
  location: MESH_EXTERNAL
  ports:
  - number: {{ .port }}
    name: https
    protocol: TLS
  resolution: DNS
{{- end }}
{{- end }}
