{{- if and .Values.istio.sidecar .Values.hosts }}
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: {{ include "tlsmonitor.fullname" . }}
spec:
  egress:
  - hosts:
    - istio-system/*
{{- range .Values.hosts }}
{{- range .target }}
    - './{{ . }}'
{{- end }}
{{- end }}
{{- if .Values.metrics.enabled }}
  ingress:
  - defaultEndpoint: '127.0.0.1:{{ .Values.metrics.port }}'
    port:
      name: http-prom
      number: {{ .Values.metrics.port }}
      protocol: HTTP
{{- end }}
  workloadSelector:
    labels:
      app: {{ .Release.Name }}
{{- end }}
