---
# TLSmonitor helm chart

image:
  repository: geckosplinter/tlsmonitor
  tag: 1.1.0
  pullPolicy: IfNotPresent

# List of endpoints to checks
hosts: []
# - port: 443
#   target:
#   - www.google.fr
# - port: 8443
#   target:
#   - www.google.com

# File certificates to check (must be secrets in the same NS)
certficateSecrets: []
# - secretName

# Frequency is hours express has int
checksFrequency: 24

# Prometheus metrics
metrics:
  enabled: true
  prometheusOperator: true
  prometheusAnnotations: false
  port: 9090
  path: /metrics

istio:
  sidecar: false
  serviceEntry: false

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

nodeAffinity.key: {}

globalLabels: {}

deployment:
  labels: {}

pod:
  labels: {}
  annotations: {}
