builds:
  - env:
      - CGO_ENABLED=0
    binary: "tlsmonitor"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
- image_templates:
  - "geckosplinter/tlsmonitor:{{ .Version }}-amd64"
  use: buildx
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "geckosplinter/tlsmonitor:{{ .Version }}-arm64v8"
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
docker_manifests:
- name_template: geckosplinter/tlsmonitor:{{ .Version }}
  image_templates:
  - geckosplinter/tlsmonitor:{{ .Version }}-amd64
  - geckosplinter/tlsmonitor:{{ .Version }}-arm64v8
