metrics:
  enabled: {{ .Values.metrics.enabled }}
  port: {{ .Values.metrics.port }}
  path: {{ .Values.metrics.path }}
{{- if .Values.hosts }}
hosts:
{{- range .Values.hosts }}
{{- $port := .port }}
{{- range .target }}
- "{{ . }}:{{ $port }}"
{{- end}}
{{- end }}
{{- end }}
{{- if .Values.certificateSecrets }}
certsPaths:
{{- range .Values.certificateSecrets }}
- "/certs/{{ . }}"
{{- end }}
{{- end }}
checksFrequency: {{ .Values.checksFrequency }}
