metrics:
  enabled: {{ .Values.metrics.enabled }}
  port: {{ .Values.metrics.port }}
  path: {{ .Values.metrics.path }}
{{- if .Values.hosts }}
hosts: {{ .Values.hosts }}
{{- end }}
{{- if .Values.certsPaths }}
certsPaths: {{ .Values.certificateSecrets }}
{{- end }}
checksFrequency: {{ .Values.checksFrequency }}
