name: Docker Image CI

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract Git Tag
      run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: docker login
      env:
        DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_HUB_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
      run: |
        echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - name: Build the Docker image
      env:
        OPTS: 'GOOS=linux GOARCH=amd64 CGO_ENABLED=0'
        IMAGE_TAG: ${{ env.GIT_TAG }}
      run: docker build --build-arg opts="${{ env.OPTS }}" . --file Dockerfile --tag "${{ secrets.DOCKER_HUB_REPOSITORY }}":$IMAGE_TAG
    - name: Docker Push
      env:
        IMAGE_TAG: ${{ env.GIT_TAG }}
      run: docker push "${{ secrets.DOCKER_HUB_REPOSITORY }}":$IMAGE_TAG
